set ::env(MILESAN_DIR) /scratch/tkovats/ssh_mnt/milesan-designs/milesan-cva6/milesan
set ::env(TRACE) trace
set ::env(INSTRUMENTATION) drfuzz_mem
set ::env(MILESAN_META_COMMON) /scratch/tkovats/ssh_mnt/milesan-meta/design-processing/common
set ::env(TOP_SOC) ariane_tiny_soc
set ::env(SV_TOP) src/ariane_tiny_soc_drfuzz_mem.sv
set ::env(SV_MEM) /scratch/tkovats/ssh_mnt/milesan-meta/design-processing/common/src/ift_sram_mem.sv
set ::env(SV_TB) dv/sv/tb_top_taints.sv
set ::env(TRACEFILE) /scratch/tkovats/ssh_mnt/milesan-data/test_trace_cva6.vcd
set ::env(SIMSRAMELF) /scratch/tkovats/ssh_mnt/milesan-data/REDUCTION_PERF/cva6/385474_cva6_22_81/rtlreduce385474_cva6_22_81_43_8_1_0.elf
set ::env(SIMSRAMTAINT) /scratch/tkovats/ssh_mnt/milesan-data/REDUCTION_PERF/cva6/385474_cva6_22_81/rtlreduce385474_cva6_22_81_43_8_1_0.simsramtaint.txt